---
- name: Clone termite git repository
  git:
    clone: true
    dest: "/home/{{ ansible_user }}/termite"
    force: true
    recursive: true
    repo: https://github.com/thestinger/termite.git

- name: Clone vte-ng git repository
  git:
    clone: true
    dest: "/home/{{ ansible_user }}/vte-ng"
    force: true
    repo: https://github.com/thestinger/vte-ng.git

- name: Install sufficient packages to compile termite
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - g++
  - libgtk-3-dev
  - gtk-doc-tools
  - gnutls-bin
  - valac
  - intltool
  - libpcre2-dev
  - libglib3.0-cil-dev
  - libgnutls28-dev
  - libgirepository1.0-dev
  - libxml2-utils
  - gperf

- name: Execute autogen.sh for vte-ng
  shell: ./autogen.sh
  args:
    chdir: "/home/{{ ansible_user }}/vte-ng/"
    environment: "LIBRARY_PATH=\"/usr/include/gtk-3.0:$LIBRARY_PATH\""

- name: Make vte-ng
  make:
    chdir: "/home/{{ ansible_user }}/vte-ng/"

- name: Make install vte-ng
  make:
    chdir: "/home/{{ ansible_user }}/vte-ng/"
    target: install

- name: Make termite
  make:
    chdir: "/home/{{ ansible_user }}/termite/"

- name: Make install termite
  make:
    chdir: "/home/{{ ansible_user }}/termite/"
    target: install

- name: execute ldconfig
  command: ldconfig

- name: Creating termite directories
  file:
    group: root
    owner: root
    mode: 0644
    dest: "/lib/terminfo/x"
    state: directory

- name: Creating soft link
  file:
    src: "/usr/local/share/terminfo/x/xterm-termite"
    dest: "/lib/terminfo/x/xterm-termite"
    state: link

